name: Deploy to Firebase Hosting (multi-site)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: ['tujhvu', 'hjdjdhdu']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Build project
        run: |
          if [ -f package.json ]; then
            npm run build 2>/dev/null || echo "No build script found, deploying as-is"
          fi

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create Firebase config
        run: |
          echo '{"projects":{"default":"student-dashboard-a4f04"}}' > .firebaserc
          cat > firebase.json <<'JSON'
          {
            "hosting": {
              "site": "${{ matrix.site }}",
              "public": ".",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**",
                "**/*.log",
                "README.md",
                "package*.json"
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ]
            }
          }
          JSON

      - name: Deploy to Firebase (${{ matrix.site }})
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccount.json
          export GOOGLE_APPLICATION_CREDENTIALS=serviceAccount.json
          firebase deploy --only hosting:${{ matrix.site }} --project student-dashboard-a4f04 --non-interactive
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
